/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test1;

public class App {

    
    public String getGreeting() {
        return "Hello World!";
    }

    public int giveAnInt() {
        return 7;
    }

    
    public static void main(String[] args) {
        
        App app = new App();
        int x = app.giveAnInt();

        System.out.println(new App().getGreeting());
        System.out.println(String.format("The int is %d", x));
        
    }
}
